### ISSUE TITLE
Nextory - USER_ALREADY_EXSISTS

### ISSUE THREAD

**Issue by NicklasWallgren** [cuardin/MasterPassword02#1]
The `/api/web/user/6.2/register` returns misspelled error codes. I thought this one was quite funny.

https://www.nextory.se/api/web/user/6.2/register?newsletter=true
{"error":{"code":6000,"msg":"USER_ALREADY_EXSISTS"},"status":401}

**Comment by cuardin** [comment]
True.
But then, programmers need not spell correctly as long as they spell consistently. :)

Also, kudos for looking me up to tell me. You don't happen to be an app developer living in Stockholm? (Or being open and able to move there on short notice) If so, we are hiring.

**Comment by NicklasWallgren** [comment]
Haha, true.

I've been working as an Android developer since 2013, but nowadays I'm focused on backend, and in particular Java/Go/Rust. Thanks anyway.
